//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_DTO.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryTwaiqWeek1Entities : DbContext
    {
        public LibraryTwaiqWeek1Entities()
            : base("name=LibraryTwaiqWeek1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
